=== AzzouziNouamane/TrekkingAgency/Allibert_Trekking.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="Client" mixed="true">
        <xs:attribute name="id" type="xs:int"></xs:attribute>
        <xs:attribute name="nom" type="xs:string"></xs:attribute>
        <xs:attribute name="prenom" type="xs:string"></xs:attribute>
        <xs:attribute name="num_CIN" type="xs:int"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="Guide" mixed="true">
        <xs:attribute name="id" type="xs:int"></xs:attribute>
        <xs:attribute name="nom" type="xs:string"></xs:attribute>
        <xs:attribute name="specialitÃ©" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="Destination" mixed="true">
        <xs:attribute name="id_dest" type="xs:int"></xs:attribute>
        <xs:attribute name="pays" type="xs:string"></xs:attribute>
        <xs:attribute name="lieu" type="xs:string"></xs:attribute>
        <xs:attribute name="continent" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="Hebergement" mixed ="true">
        <xs:attribute name="id" type="xs:int"></xs:attribute>
        <xs:attribute name="type" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="Activite">
        <xs:attribute name="id" type="xs:int"></xs:attribute>
        <xs:attribute name="type" type="xs:string"></xs:attribute>
        <xs:attribute name="niveau" type="xs:int"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="Reservation">
        <xs:sequence>
            <xs:element name="enrolled" type="Enrolled">
            </xs:element>
        </xs:sequence>
        <xs:attribute name="prix" type="xs:int"/>
        <xs:attribute name="effectif" type="xs:int"/>
        <xs:attribute name="depart" type="xs:string"/>
        <xs:attribute name="retour" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="Enrolled">
        <xs:sequence>
            <xs:element name="client" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id" type="xs:int"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dest">
        <xs:sequence>
            <xs:element name="destination" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="id_dest" type="xs:int"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Misc">
        <xs:sequence>
            <xs:element name="weather" type="xs:string"></xs:element>
            <xs:element name="currency" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>

     




    <xs:element name="agency">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="clients">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="client" maxOccurs="unbounded" type="Client">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="guides">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="guide" maxOccurs="unbounded" type="Guide">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="destinations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="destination" maxOccurs="unbounded" type="Destination">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="hebergements">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="hebergement" maxOccurs="unbounded" type="Hebergement">

                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="activites">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="activite" maxOccurs="unbounded" type="Activite">
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="trips">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="trip">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="destinations" maxOccurs="unbounded" type="dest">

                                        </xs:element>
                                        <xs:element name="summary">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="description" type="xs:string"></xs:element>
                                                    <xs:element name="duration" type="xs:string"></xs:element>
                                                    <xs:element name="hebergements">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="hebergement" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:attribute name="id" type="xs:int"></xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="progression">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="day" maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="activities">
                                                                                <xs:complexType>
                                                                                    <xs:sequence>
                                                                                        <xs:element name="activite">
                                                                                            <xs:complexType>
                                                                                                <xs:attribute name="id" type="xs:int"></xs:attribute>
                                                                                            </xs:complexType>
                                                                                        </xs:element>
                                                                                    </xs:sequence>
                                                                                </xs:complexType>
                                                                            </xs:element>
                                                                        </xs:sequence>
                                                                        <xs:attribute name="number" type="xs:int"></xs:attribute>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="miscellaneous" maxOccurs="unbounded" type="Misc">
                             
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="guides">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="guide">
                                                        <xs:complexType>
                                                            <xs:attribute name="id" type="xs:int"></xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="reservations">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="reservation" maxOccurs="unbounded" type="Reservation">
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="reviews">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="review" maxOccurs="unbounded">
                                                        <xs:complexType>

                                                            <xs:attribute name="date" type="xs:string"></xs:attribute>
                                                            <xs:attribute name="content" type="xs:string"></xs:attribute>
                                                            <xs:attribute name="client-id" type="xs:int"></xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

        </xs:complexType>
        <xs:key name="clientID">
            <xs:selector xpath="./clients/client"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="DestinationID">
            <xs:selector xpath="./destinations/destination"/>
            <xs:field xpath="@id_dest"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== AzzouziNouamane/TrekkingAgency/Allibert_Trekking.xml
<?xml version="1.0" encoding="UTF-8"?>
<agency xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Allibert_Trekking.xsd">
    <clients>
        <client id="1" nom="Mahjoub" prenom="Nidhal" num_CIN="1234"></client>
        <client id="2" nom="Azzouzi" prenom="Nouamane" num_CIN="5678"></client>
        <client id="3" nom="Morgan" prenom="Arthur" num_CIN="8765"></client>
        <client id="4" nom="Marston" prenom="John" num_CIN="4321"></client>



    </clients>

    <guides>
        <guide id="1" nom="Alexandre" specialité="Afrique"/>
        <guide id="1" nom="Julien" specialité="Afrique"/>
    </guides>

    <destinations>
        <destination id_dest="1" pays="Egypte" lieu="Le Caire" continent="Afrique"></destination>
        <destination id_dest="2" pays="Maroc" lieu="Desert" continent="Afrique"></destination>
        <destination id_dest="3" pays="Namibie" lieu="Safari" continent="Afrique"></destination>
        <destination id_dest="4" pays="Zimbabwe" lieu="Safari" continent="Afrique"></destination>
    </destinations>

    <hebergements>
        <hebergement id="1" type = "Hotel"/>
        <hebergement id="2" type = "Camping"/>
        <hebergement id="3" type = "AirBnB"/>
    </hebergements>

    <activites>
        <activite id="1" type = "Voyage" niveau="1"/>
        <activite id="2" type = "Musée" niveau="2"/>
        <activite id="3" type = "Randonné" niveau="3"/>
        <activite id="4" type = "Repos" niveau="2"/>
    </activites>


    <trips>
        <trip>
            <destinations>
                <destination id_dest="1"/>
            </destinations>
            <summary>
                <description>
                Les plus beaux sites de l’Egypte ancienne réunis dans un voyage complet :
                — vestiges et bibliothèques d’Alexandrie,
                — sphinx, pyramides de Guiseh et Saqqarah, musée et vieux Caire 
                — villages et jardins nubiens, Abu Simbel et les plus beaux temples au fil du Nil.
                </description>
                <duration>11 Jours</duration>
                <hebergements>
                    <hebergement id="1"/>
                    <hebergement id="2"/>
                </hebergements>
                <progression>
                    <day number="1">
                        <activities>
                            <activite id="1"></activite>
                        </activities>
                    </day>
                    <day number="2">
                        <activities>
                            <activite id="3"/>
                        </activities>
                    </day>
                    <day number="3">
                        <activities>
                            <activite id="4"/>
                        </activities>
                    </day>
                                </progression>
                <miscellaneous>
                    <weather>Climat méditerranéen</weather>
                    <currency>Livre égyptienne</currency>
                </miscellaneous>

            </summary>
            <guides>
                <guide id ="1"/>
            </guides>
            <reservations>
                <reservation prix ="1000" effectif="2" depart="26/11/2019" retour="06/12/2019">
                    <enrolled>
                        <client id="1"/>
                        <client id="2"/>
                    </enrolled>
                </reservation>
                <reservation prix ="1700" effectif="2" depart="09/12/2019" retour="25/12/2019">
                    <enrolled>
                        <client id="3"/>
                        <client id="4"/>
                    </enrolled>
                </reservation>
            </reservations>
            <reviews>
                <review date="10/12/2019" client-id="1" content="Cool"/>
                
                <review date="27/12/2019" client-id="3" content="Nice"/>
                
            </reviews>
        </trip>
    </trips>

</agency>
